services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextcode_web
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.4
    container_name: nextcode_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: nextcode
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - nextcode_data:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - "-h"
        - localhost
        - "-proot"
      interval: 5s
      timeout: 5s
      retries: 20

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: nextcode_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy

volumes:
  nextcode_data: